// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/rulessly/gin-base/internal/ent/schema"
	"github.com/rulessly/gin-base/internal/ent/systemuser"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	systemuserMixin := schema.SystemUser{}.Mixin()
	systemuserMixinFields0 := systemuserMixin[0].Fields()
	_ = systemuserMixinFields0
	systemuserFields := schema.SystemUser{}.Fields()
	_ = systemuserFields
	// systemuserDescCreateTime is the schema descriptor for create_time field.
	systemuserDescCreateTime := systemuserMixinFields0[0].Descriptor()
	// systemuser.DefaultCreateTime holds the default value on creation for the create_time field.
	systemuser.DefaultCreateTime = systemuserDescCreateTime.Default.(func() time.Time)
	// systemuserDescUpdateTime is the schema descriptor for update_time field.
	systemuserDescUpdateTime := systemuserMixinFields0[1].Descriptor()
	// systemuser.DefaultUpdateTime holds the default value on creation for the update_time field.
	systemuser.DefaultUpdateTime = systemuserDescUpdateTime.Default.(func() time.Time)
	// systemuser.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	systemuser.UpdateDefaultUpdateTime = systemuserDescUpdateTime.UpdateDefault.(func() time.Time)
	// systemuserDescAvatar is the schema descriptor for avatar field.
	systemuserDescAvatar := systemuserFields[4].Descriptor()
	// systemuser.DefaultAvatar holds the default value on creation for the avatar field.
	systemuser.DefaultAvatar = systemuserDescAvatar.Default.(string)
	// systemuserDescEmail is the schema descriptor for email field.
	systemuserDescEmail := systemuserFields[5].Descriptor()
	// systemuser.DefaultEmail holds the default value on creation for the email field.
	systemuser.DefaultEmail = systemuserDescEmail.Default.(string)
	// systemuserDescPhone is the schema descriptor for phone field.
	systemuserDescPhone := systemuserFields[6].Descriptor()
	// systemuser.DefaultPhone holds the default value on creation for the phone field.
	systemuser.DefaultPhone = systemuserDescPhone.Default.(string)
	// systemuserDescCreator is the schema descriptor for creator field.
	systemuserDescCreator := systemuserFields[7].Descriptor()
	// systemuser.DefaultCreator holds the default value on creation for the creator field.
	systemuser.DefaultCreator = systemuserDescCreator.Default.(string)
}
