// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rulessly/gin-base/internal/ent/predicate"
	"github.com/rulessly/gin-base/internal/ent/systemuser"
)

// SystemUserUpdate is the builder for updating SystemUser entities.
type SystemUserUpdate struct {
	config
	hooks    []Hook
	mutation *SystemUserMutation
}

// Where appends a list predicates to the SystemUserUpdate builder.
func (suu *SystemUserUpdate) Where(ps ...predicate.SystemUser) *SystemUserUpdate {
	suu.mutation.Where(ps...)
	return suu
}

// SetUpdateTime sets the "update_time" field.
func (suu *SystemUserUpdate) SetUpdateTime(t time.Time) *SystemUserUpdate {
	suu.mutation.SetUpdateTime(t)
	return suu
}

// SetUsername sets the "username" field.
func (suu *SystemUserUpdate) SetUsername(s string) *SystemUserUpdate {
	suu.mutation.SetUsername(s)
	return suu
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (suu *SystemUserUpdate) SetNillableUsername(s *string) *SystemUserUpdate {
	if s != nil {
		suu.SetUsername(*s)
	}
	return suu
}

// SetPassword sets the "password" field.
func (suu *SystemUserUpdate) SetPassword(s string) *SystemUserUpdate {
	suu.mutation.SetPassword(s)
	return suu
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (suu *SystemUserUpdate) SetNillablePassword(s *string) *SystemUserUpdate {
	if s != nil {
		suu.SetPassword(*s)
	}
	return suu
}

// SetNickname sets the "nickname" field.
func (suu *SystemUserUpdate) SetNickname(s string) *SystemUserUpdate {
	suu.mutation.SetNickname(s)
	return suu
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (suu *SystemUserUpdate) SetNillableNickname(s *string) *SystemUserUpdate {
	if s != nil {
		suu.SetNickname(*s)
	}
	return suu
}

// SetRole sets the "role" field.
func (suu *SystemUserUpdate) SetRole(i int8) *SystemUserUpdate {
	suu.mutation.ResetRole()
	suu.mutation.SetRole(i)
	return suu
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (suu *SystemUserUpdate) SetNillableRole(i *int8) *SystemUserUpdate {
	if i != nil {
		suu.SetRole(*i)
	}
	return suu
}

// AddRole adds i to the "role" field.
func (suu *SystemUserUpdate) AddRole(i int8) *SystemUserUpdate {
	suu.mutation.AddRole(i)
	return suu
}

// SetAvatar sets the "avatar" field.
func (suu *SystemUserUpdate) SetAvatar(s string) *SystemUserUpdate {
	suu.mutation.SetAvatar(s)
	return suu
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (suu *SystemUserUpdate) SetNillableAvatar(s *string) *SystemUserUpdate {
	if s != nil {
		suu.SetAvatar(*s)
	}
	return suu
}

// ClearAvatar clears the value of the "avatar" field.
func (suu *SystemUserUpdate) ClearAvatar() *SystemUserUpdate {
	suu.mutation.ClearAvatar()
	return suu
}

// SetEmail sets the "email" field.
func (suu *SystemUserUpdate) SetEmail(s string) *SystemUserUpdate {
	suu.mutation.SetEmail(s)
	return suu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (suu *SystemUserUpdate) SetNillableEmail(s *string) *SystemUserUpdate {
	if s != nil {
		suu.SetEmail(*s)
	}
	return suu
}

// ClearEmail clears the value of the "email" field.
func (suu *SystemUserUpdate) ClearEmail() *SystemUserUpdate {
	suu.mutation.ClearEmail()
	return suu
}

// SetPhone sets the "phone" field.
func (suu *SystemUserUpdate) SetPhone(s string) *SystemUserUpdate {
	suu.mutation.SetPhone(s)
	return suu
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (suu *SystemUserUpdate) SetNillablePhone(s *string) *SystemUserUpdate {
	if s != nil {
		suu.SetPhone(*s)
	}
	return suu
}

// ClearPhone clears the value of the "phone" field.
func (suu *SystemUserUpdate) ClearPhone() *SystemUserUpdate {
	suu.mutation.ClearPhone()
	return suu
}

// SetCreator sets the "creator" field.
func (suu *SystemUserUpdate) SetCreator(s string) *SystemUserUpdate {
	suu.mutation.SetCreator(s)
	return suu
}

// SetNillableCreator sets the "creator" field if the given value is not nil.
func (suu *SystemUserUpdate) SetNillableCreator(s *string) *SystemUserUpdate {
	if s != nil {
		suu.SetCreator(*s)
	}
	return suu
}

// ClearCreator clears the value of the "creator" field.
func (suu *SystemUserUpdate) ClearCreator() *SystemUserUpdate {
	suu.mutation.ClearCreator()
	return suu
}

// Mutation returns the SystemUserMutation object of the builder.
func (suu *SystemUserUpdate) Mutation() *SystemUserMutation {
	return suu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (suu *SystemUserUpdate) Save(ctx context.Context) (int, error) {
	suu.defaults()
	return withHooks(ctx, suu.sqlSave, suu.mutation, suu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suu *SystemUserUpdate) SaveX(ctx context.Context) int {
	affected, err := suu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (suu *SystemUserUpdate) Exec(ctx context.Context) error {
	_, err := suu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suu *SystemUserUpdate) ExecX(ctx context.Context) {
	if err := suu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suu *SystemUserUpdate) defaults() {
	if _, ok := suu.mutation.UpdateTime(); !ok {
		v := systemuser.UpdateDefaultUpdateTime()
		suu.mutation.SetUpdateTime(v)
	}
}

func (suu *SystemUserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(systemuser.Table, systemuser.Columns, sqlgraph.NewFieldSpec(systemuser.FieldID, field.TypeInt))
	if ps := suu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suu.mutation.UpdateTime(); ok {
		_spec.SetField(systemuser.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := suu.mutation.Username(); ok {
		_spec.SetField(systemuser.FieldUsername, field.TypeString, value)
	}
	if value, ok := suu.mutation.Password(); ok {
		_spec.SetField(systemuser.FieldPassword, field.TypeString, value)
	}
	if value, ok := suu.mutation.Nickname(); ok {
		_spec.SetField(systemuser.FieldNickname, field.TypeString, value)
	}
	if value, ok := suu.mutation.Role(); ok {
		_spec.SetField(systemuser.FieldRole, field.TypeInt8, value)
	}
	if value, ok := suu.mutation.AddedRole(); ok {
		_spec.AddField(systemuser.FieldRole, field.TypeInt8, value)
	}
	if value, ok := suu.mutation.Avatar(); ok {
		_spec.SetField(systemuser.FieldAvatar, field.TypeString, value)
	}
	if suu.mutation.AvatarCleared() {
		_spec.ClearField(systemuser.FieldAvatar, field.TypeString)
	}
	if value, ok := suu.mutation.Email(); ok {
		_spec.SetField(systemuser.FieldEmail, field.TypeString, value)
	}
	if suu.mutation.EmailCleared() {
		_spec.ClearField(systemuser.FieldEmail, field.TypeString)
	}
	if value, ok := suu.mutation.Phone(); ok {
		_spec.SetField(systemuser.FieldPhone, field.TypeString, value)
	}
	if suu.mutation.PhoneCleared() {
		_spec.ClearField(systemuser.FieldPhone, field.TypeString)
	}
	if value, ok := suu.mutation.Creator(); ok {
		_spec.SetField(systemuser.FieldCreator, field.TypeString, value)
	}
	if suu.mutation.CreatorCleared() {
		_spec.ClearField(systemuser.FieldCreator, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, suu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	suu.mutation.done = true
	return n, nil
}

// SystemUserUpdateOne is the builder for updating a single SystemUser entity.
type SystemUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SystemUserMutation
}

// SetUpdateTime sets the "update_time" field.
func (suuo *SystemUserUpdateOne) SetUpdateTime(t time.Time) *SystemUserUpdateOne {
	suuo.mutation.SetUpdateTime(t)
	return suuo
}

// SetUsername sets the "username" field.
func (suuo *SystemUserUpdateOne) SetUsername(s string) *SystemUserUpdateOne {
	suuo.mutation.SetUsername(s)
	return suuo
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (suuo *SystemUserUpdateOne) SetNillableUsername(s *string) *SystemUserUpdateOne {
	if s != nil {
		suuo.SetUsername(*s)
	}
	return suuo
}

// SetPassword sets the "password" field.
func (suuo *SystemUserUpdateOne) SetPassword(s string) *SystemUserUpdateOne {
	suuo.mutation.SetPassword(s)
	return suuo
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (suuo *SystemUserUpdateOne) SetNillablePassword(s *string) *SystemUserUpdateOne {
	if s != nil {
		suuo.SetPassword(*s)
	}
	return suuo
}

// SetNickname sets the "nickname" field.
func (suuo *SystemUserUpdateOne) SetNickname(s string) *SystemUserUpdateOne {
	suuo.mutation.SetNickname(s)
	return suuo
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (suuo *SystemUserUpdateOne) SetNillableNickname(s *string) *SystemUserUpdateOne {
	if s != nil {
		suuo.SetNickname(*s)
	}
	return suuo
}

// SetRole sets the "role" field.
func (suuo *SystemUserUpdateOne) SetRole(i int8) *SystemUserUpdateOne {
	suuo.mutation.ResetRole()
	suuo.mutation.SetRole(i)
	return suuo
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (suuo *SystemUserUpdateOne) SetNillableRole(i *int8) *SystemUserUpdateOne {
	if i != nil {
		suuo.SetRole(*i)
	}
	return suuo
}

// AddRole adds i to the "role" field.
func (suuo *SystemUserUpdateOne) AddRole(i int8) *SystemUserUpdateOne {
	suuo.mutation.AddRole(i)
	return suuo
}

// SetAvatar sets the "avatar" field.
func (suuo *SystemUserUpdateOne) SetAvatar(s string) *SystemUserUpdateOne {
	suuo.mutation.SetAvatar(s)
	return suuo
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (suuo *SystemUserUpdateOne) SetNillableAvatar(s *string) *SystemUserUpdateOne {
	if s != nil {
		suuo.SetAvatar(*s)
	}
	return suuo
}

// ClearAvatar clears the value of the "avatar" field.
func (suuo *SystemUserUpdateOne) ClearAvatar() *SystemUserUpdateOne {
	suuo.mutation.ClearAvatar()
	return suuo
}

// SetEmail sets the "email" field.
func (suuo *SystemUserUpdateOne) SetEmail(s string) *SystemUserUpdateOne {
	suuo.mutation.SetEmail(s)
	return suuo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (suuo *SystemUserUpdateOne) SetNillableEmail(s *string) *SystemUserUpdateOne {
	if s != nil {
		suuo.SetEmail(*s)
	}
	return suuo
}

// ClearEmail clears the value of the "email" field.
func (suuo *SystemUserUpdateOne) ClearEmail() *SystemUserUpdateOne {
	suuo.mutation.ClearEmail()
	return suuo
}

// SetPhone sets the "phone" field.
func (suuo *SystemUserUpdateOne) SetPhone(s string) *SystemUserUpdateOne {
	suuo.mutation.SetPhone(s)
	return suuo
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (suuo *SystemUserUpdateOne) SetNillablePhone(s *string) *SystemUserUpdateOne {
	if s != nil {
		suuo.SetPhone(*s)
	}
	return suuo
}

// ClearPhone clears the value of the "phone" field.
func (suuo *SystemUserUpdateOne) ClearPhone() *SystemUserUpdateOne {
	suuo.mutation.ClearPhone()
	return suuo
}

// SetCreator sets the "creator" field.
func (suuo *SystemUserUpdateOne) SetCreator(s string) *SystemUserUpdateOne {
	suuo.mutation.SetCreator(s)
	return suuo
}

// SetNillableCreator sets the "creator" field if the given value is not nil.
func (suuo *SystemUserUpdateOne) SetNillableCreator(s *string) *SystemUserUpdateOne {
	if s != nil {
		suuo.SetCreator(*s)
	}
	return suuo
}

// ClearCreator clears the value of the "creator" field.
func (suuo *SystemUserUpdateOne) ClearCreator() *SystemUserUpdateOne {
	suuo.mutation.ClearCreator()
	return suuo
}

// Mutation returns the SystemUserMutation object of the builder.
func (suuo *SystemUserUpdateOne) Mutation() *SystemUserMutation {
	return suuo.mutation
}

// Where appends a list predicates to the SystemUserUpdate builder.
func (suuo *SystemUserUpdateOne) Where(ps ...predicate.SystemUser) *SystemUserUpdateOne {
	suuo.mutation.Where(ps...)
	return suuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suuo *SystemUserUpdateOne) Select(field string, fields ...string) *SystemUserUpdateOne {
	suuo.fields = append([]string{field}, fields...)
	return suuo
}

// Save executes the query and returns the updated SystemUser entity.
func (suuo *SystemUserUpdateOne) Save(ctx context.Context) (*SystemUser, error) {
	suuo.defaults()
	return withHooks(ctx, suuo.sqlSave, suuo.mutation, suuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suuo *SystemUserUpdateOne) SaveX(ctx context.Context) *SystemUser {
	node, err := suuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suuo *SystemUserUpdateOne) Exec(ctx context.Context) error {
	_, err := suuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suuo *SystemUserUpdateOne) ExecX(ctx context.Context) {
	if err := suuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suuo *SystemUserUpdateOne) defaults() {
	if _, ok := suuo.mutation.UpdateTime(); !ok {
		v := systemuser.UpdateDefaultUpdateTime()
		suuo.mutation.SetUpdateTime(v)
	}
}

func (suuo *SystemUserUpdateOne) sqlSave(ctx context.Context) (_node *SystemUser, err error) {
	_spec := sqlgraph.NewUpdateSpec(systemuser.Table, systemuser.Columns, sqlgraph.NewFieldSpec(systemuser.FieldID, field.TypeInt))
	id, ok := suuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SystemUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, systemuser.FieldID)
		for _, f := range fields {
			if !systemuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != systemuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suuo.mutation.UpdateTime(); ok {
		_spec.SetField(systemuser.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := suuo.mutation.Username(); ok {
		_spec.SetField(systemuser.FieldUsername, field.TypeString, value)
	}
	if value, ok := suuo.mutation.Password(); ok {
		_spec.SetField(systemuser.FieldPassword, field.TypeString, value)
	}
	if value, ok := suuo.mutation.Nickname(); ok {
		_spec.SetField(systemuser.FieldNickname, field.TypeString, value)
	}
	if value, ok := suuo.mutation.Role(); ok {
		_spec.SetField(systemuser.FieldRole, field.TypeInt8, value)
	}
	if value, ok := suuo.mutation.AddedRole(); ok {
		_spec.AddField(systemuser.FieldRole, field.TypeInt8, value)
	}
	if value, ok := suuo.mutation.Avatar(); ok {
		_spec.SetField(systemuser.FieldAvatar, field.TypeString, value)
	}
	if suuo.mutation.AvatarCleared() {
		_spec.ClearField(systemuser.FieldAvatar, field.TypeString)
	}
	if value, ok := suuo.mutation.Email(); ok {
		_spec.SetField(systemuser.FieldEmail, field.TypeString, value)
	}
	if suuo.mutation.EmailCleared() {
		_spec.ClearField(systemuser.FieldEmail, field.TypeString)
	}
	if value, ok := suuo.mutation.Phone(); ok {
		_spec.SetField(systemuser.FieldPhone, field.TypeString, value)
	}
	if suuo.mutation.PhoneCleared() {
		_spec.ClearField(systemuser.FieldPhone, field.TypeString)
	}
	if value, ok := suuo.mutation.Creator(); ok {
		_spec.SetField(systemuser.FieldCreator, field.TypeString, value)
	}
	if suuo.mutation.CreatorCleared() {
		_spec.ClearField(systemuser.FieldCreator, field.TypeString)
	}
	_node = &SystemUser{config: suuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suuo.mutation.done = true
	return _node, nil
}
